### ISSUE TITLE
Error: failure

### ISSUE THREAD

**Issue by KirkBushman** [dobbydog/sftp-sync-deploy#12]
Hi, when I run the script like in the example, once I arrive at a quarter of the way in I get an error:

    error!  { Error: Failure
        at SFTPStream._transform (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/sftp.js:410:27)
        at SFTPStream.Transform._read (_stream_transform.js:190:10)
        at SFTPStream._read (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/sftp.js:181:15)
        at SFTPStream.Transform._write (_stream_transform.js:178:12)
        at doWrite (_stream_writable.js:410:12)
        at writeOrBuffer (_stream_writable.js:394:5)
        at SFTPStream.Writable.write (_stream_writable.js:294:11)
        at Channel.ondata (_stream_readable.js:666:20)
        at Channel.emit (events.js:182:13)
        at addChunk (_stream_readable.js:283:12)
        at readableAddChunk (_stream_readable.js:264:11)
        at Channel.Readable.push (_stream_readable.js:219:10)
        at SSH2Stream.<anonymous> (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2/lib/Channel.js:166:15)
        at SSH2Stream.emit (events.js:182:13)
        at parsePacket (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/ssh.js:3444:10)
        at SSH2Stream._transform (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/ssh.js:669:13)
      cause:
       { Error: Failure
           at SFTPStream._transform (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/sftp.js:410:27)
           at SFTPStream.Transform._read (_stream_transform.js:190:10)
           at SFTPStream._read (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/sftp.js:181:15)
           at SFTPStream.Transform._write (_stream_transform.js:178:12)
           at doWrite (_stream_writable.js:410:12)
           at writeOrBuffer (_stream_writable.js:394:5)
           at SFTPStream.Writable.write (_stream_writable.js:294:11)
           at Channel.ondata (_stream_readable.js:666:20)
           at Channel.emit (events.js:182:13)
           at addChunk (_stream_readable.js:283:12)
           at readableAddChunk (_stream_readable.js:264:11)
           at Channel.Readable.push (_stream_readable.js:219:10)
           at SSH2Stream.<anonymous> (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2/lib/Channel.js:166:15)
           at SSH2Stream.emit (events.js:182:13)
           at parsePacket (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/ssh.js:3444:10)
           at SSH2Stream._transform (/home/user/Documents/projects/controlPanel/backend/node_modules/ssh2-streams/lib/ssh.js:669:13) code: 4, lang: '' },
      isOperational: true,
      code: 4,
      lang: '' }    

Am I doing something wrong? it's working in the node_modules directory...

**Comment by dobbydog** [comment]
Perhaps same as #8 #11 
Can you give it a try new beta version?
`npm i sftp-sync-deploy@beta`

**Comment by KirkBushman** [comment]
Using that version it just hangs, with no error at all.
I'm trying to deploy a node project, the last line is every time:

      node_modules/npm/node_modules/node-gyp

**Comment by Dids** [comment]
Latest beta seems to work here.
