### ISSUE TITLE
Error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by noraj** [dobbydog/sftp-sync-deploy#19]
```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Cannot parse privateKey: Unsupported key format
    at Client.connect (/home/noraj/Dev/blog-ekip/node_modules/ssh2/lib/client.js:230:13)
    at /home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:58:18
    at new Promise (<anonymous>)
    at SftpSync.connect (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:49:16)
    at SftpSync.<anonymous> (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:305:28)
    at Generator.next (<anonymous>)
    at /home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:3:12)
    at SftpSync.initQueuifiedSftp (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:300:16)
    at SftpSync.<anonymous> (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:216:28)
    at Generator.next (<anonymous>)
    at /home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:3:12)
    at SftpSync.buildSyncTable (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:214:16)
    at SftpSync.<anonymous> (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:81:38)
    at Generator.next (<anonymous>)
    at /home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:3:12)
    at SftpSync.sync (/home/noraj/Dev/blog-ekip/node_modules/sftp-sync-deploy/lib/sftpSync.js:80:16)
```

I provided an absolute path `'/home/noraj/.ssh/id_ed25519_key'`.

You are using ssh2 nodejs lib (https://github.com/mscdex/ssh2).

The key is in the expected PEM format but you are not checking the key type. sshé can handle any time of key:

![image](https://user-images.githubusercontent.com/16578570/75709332-c19e2880-5cc2-11ea-9ce1-8c51679a3222.png)

I'm using `ed25519` not RSA but you're not checking the type so it expect RSA.

**Comment by lyh543** [comment]
Similar problem here.

```
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Connection Error: read ECONNRESET
    at Client.client.on.on.err_1 (/home/runner/work/lyh543.github.io.backup/lyh543.github.io.backup/node_modules/sftp-sync-deploy/lib/sftpSync.js:56:24)
    at Client.emit (events.js:198:13)
    at Socket.<anonymous> (/home/runner/work/lyh543.github.io.backup/lyh543.github.io.backup/node_modules/ssh2/lib/client.js:299:10)
    at Socket.emit (events.js:203:15)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Error: Process completed with exit code 2.
```

Here's my solution:

I banned the `ed25519` identification on the SFTP server by commenting the below line in `/etc/ssh/sshd_config`:

```sh
# HostKey /etc/ssh/ssh_host_ed25519_key
```

Then I restarted `sshd` and deployed again, successfully.

However, **it will change the SSH identification of the host**. After the operation, you need to run `ssh-keygen -R <SFTP server domain>` on **every device** that had connected to the SFTP server before.
